# Site settings
title : Dustin Talk
email: dwtalk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dustinwtalk.com" # the base hostname & protocol for your site
twitter_username: DustinTalk
github_username:  dwtalk

pygment: true

permalink: /:categories/:year/:month/:day/:title 

exclude: [oldsite, node_modules, Gruntfile.js, package.json, ".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Build settings
markdown: kramdown

JB :
  version : 0.3.0

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : dustinwtalk

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-39578201-1'