permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Dustin Talk
tagline: the blog of Dustin Talk
author :
  name : Dustin Talk
  github : dwtalk
  twitter : DustinTalk

production_url : http://dustinwtalk.com

JB :
  version : 0.3.0

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : dustinwtalk

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
  
  sharing :
    provider : false

